services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://kevin:SecureP@ssw0rd@postgres:5432/linksdb
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=kevin
      - POSTGRES_PASSWORD=SecureP@ssw0rd
      - POSTGRES_DB=linksdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
